-- Test Purpose: Verify V$TABLESPACES exposes MRDB TDE phase 1 metadata.
-- Checks: Tablespace exists, is marked encrypted, and has algorithm plus key id.
-- Manual reference:
--   doc/altibase-docs/Manuals/Altibase_trunk/eng/iSQL User's Manual.md
SELECT CASE WHEN COUNT(*) = 1 THEN 1 ELSE 0 END AS PASS_COUNT FROM V$TABLESPACES WHERE NAME = 'TDE_SQLT_TBS';
SELECT CASE WHEN COUNT(*) = 1 THEN 1 ELSE 0 END AS PASS_DISTINCT FROM V$TABLESPACES WHERE NAME = 'TDE_SQLT_TBS' AND IS_ENCRYPTED = 1;
SELECT CASE WHEN COUNT(*) = 1 THEN 1 ELSE 0 END AS PASS_HASH_RESTORE FROM V$TABLESPACES WHERE NAME = 'TDE_SQLT_TBS' AND ENCRYPT_ALGORITHM = 'AES-256-CTR' AND MASTER_KEY_ID > 0;
