-- Crash repro converted from legacy sql harness.
-- Original semantics preserved:
--   1) only LOOP expansion changed
--   2) repeated INSERT statements remain separate executions
--   3) SELECT shape and hint text are kept close to the source
-- Expected on affected build:
--   abnormal termination / server disconnect during one of the SELECT statements

--+SKIP BEGIN;
drop table t1;
--+SKIP END;

-- ########################################
-- #1.small
-- ########################################
create table t1(i1 integer, i2 integer);
insert into t1 select rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum from dual connect by level <= 5;
create index idx1 on t1(i1);

select i1 from (select /*+materialize index(t1 idx1)*/ i1, i2 from t1);

drop table t1;
create table t1(i1 integer, i2 integer) tablespace sys_tbs_disk_data;
insert into t1 select rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum from dual connect by level <= 5;
create index idx1 on t1(i1);

select i1 from (select /*+materialize index(t1 idx1)*/ i1, i2 from t1);

-- ########################################
-- #2.large
-- ########################################
drop table t1;
create table t1(i1 integer, i2 integer, i3 char(7000));
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
create index idx1 on t1(i1);

select i1 from (select /*+materialize index(t1 idx1) index(t1 idx1) */ i1, i2 from t1);

drop table t1;
create table t1(i1 integer, i2 integer, i3 char(7000) ) tablespace sys_tbs_disk_data;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
create index idx1 on t1(i1);

select i1 from (select /*+materialize index(t1 idx1) index(t1 idx1)*/ i1, i2 from t1);

-- ########################################
-- #3.huge
-- ########################################
drop table t1;
create table t1(i1 char(1024), i2 char(10000), i3 char(10000) );
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
create index idx1 on t1(i1);

select i1 from (select /*+materialize index(t1 idx1) index(t1 idx1)*/ i1, i2, i3 from t1);

drop table t1;
create table t1(i1 char(1024), i2 char(10000), i3 char(10000) ) tablespace sys_tbs_disk_data;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
create index idx1 on t1(i1);

select i1 from (select /*+materialize index(t1 idx1) index(t1 idx1)*/ i1, i2, i3 from t1);

-- ########################################
-- #4.small-many
-- ########################################
drop table t1;
create table t1(i1 integer, i2 integer, i3 char(1024));
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
create index idx1 on t1(i1);

select i1 from (select /*+materialize index(t1 idx1) index(t1 idx1) */ i1, i2 from t1);

drop table t1;
create table t1(i1 integer, i2 integer, i3 char(1024)) tablespace sys_tbs_disk_data;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
create index idx1 on t1(i1);

select i1 from (select /*+materialize index(t1 idx1) index(t1 idx1) */ i1, i2 from t1);

-- ########################################
-- #5.huge-many
-- ########################################
drop table t1;
create table t1(i1 char(1024), i2 char(10000), i3 char(10000) );
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
create index idx1 on t1(i1);

select i1 from (select /*+materialize index(t1 idx1) */ i1, i2, i3 from t1);

drop table t1;
create table t1(i1 char(1024), i2 char(10000), i3 char(10000)) tablespace sys_tbs_disk_data;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
insert into t1 select rownum,rownum,rownum from dual connect by level <= 5;
create index idx1 on t1(i1);

select i1 from (select /*+materialize index(t1 idx1) */ i1, i2, i3 from t1);
drop table t1;
