-- Reference: doc/altibase-docs/Manuals/Altibase_trunk/eng/iSQL User's Manual.md
--+TIMEOUT_SEC 600;
--+SYSTEM bash ./tests/tde/bin/tde_case.sh bootstrap_init;

ALTER SYSTEM TDE CREATE KEYSTORE;
ALTER SYSTEM TDE CREATE MASTER KEY;

CREATE MEMORY TABLESPACE TDE_SQLT_TBS
SIZE 64M
AUTOEXTEND OFF
ENCRYPTION;

CREATE TABLE TDE_SQLT_T
(
    I INTEGER PRIMARY KEY,
    V VARCHAR(32)
)
TABLESPACE TDE_SQLT_TBS;

INSERT INTO TDE_SQLT_T VALUES (1, 'alpha');
INSERT INTO TDE_SQLT_T VALUES (2, 'beta');
COMMIT;

ALTER SYSTEM CHECKPOINT;
