--+TIMEOUT_SEC 600;
-- Test Purpose: Cross-check general and dedicated TDE views for the base tablespace.
-- Checks: View rows match and the operation view is idle.
-- Manual reference:
--   doc/altibase-docs/Manuals/Altibase_trunk/eng/iSQL User's Manual.md
SELECT CASE WHEN COUNT(*) = 1 THEN 1 ELSE 0 END AS PASS_GENERAL_VIEW FROM V$TABLESPACES WHERE NAME = 'TDE_SQLT_TBS' AND IS_ENCRYPTED = 1;
SELECT CASE WHEN COUNT(*) = 1 THEN 1 ELSE 0 END AS PASS_TDE_VIEW FROM V$TDE_TABLESPACES WHERE NAME = 'TDE_SQLT_TBS' AND IS_ENCRYPTED = 1 AND MASTER_KEY_ID = (SELECT MASTER_KEY_ID FROM V$TABLESPACES WHERE NAME = 'TDE_SQLT_TBS');
SELECT CASE WHEN COUNT(*) = 1 THEN 1 ELSE 0 END AS PASS_MASTER_KEY_VIEW FROM V$TDE_MASTER_KEYS WHERE IS_ACTIVE = 1 AND REFERENCED_TABLESPACE_COUNT = 1;
SELECT CASE WHEN COUNT(*) = 1 THEN 1 ELSE 0 END AS PASS_IDLE_OPERATION FROM V$TDE_OPERATION WHERE OPERATION = 'NONE' AND STATE = 'IDLE';