-- Test Purpose: Reproduce mode2 packed-row sort-join regression fixed by sdtSortModule callback row conversion.
-- Checks: USE_SORT join result must match baseline in both mode1 and mode2.
-- Manual reference:
--   docs/manuals/altibase/Altibase_7.1/eng/iSQL User's Manual.md
--   docs/manuals/altibase/Altibase_7.1/eng/Performance Tuning Guide.md

--+TIMEOUT_SEC 600;
--+SKIP BEGIN;
DROP TABLE DST_COV20_ITEM_2;
DROP TABLE DST_COV20_STORE_SALES_2;
--+SKIP END;

CREATE TABLE DST_COV20_ITEM_2
(
    I_ITEM_SK   INTEGER NOT NULL,
    I_CLASS     CHAR(50),
    CONSTRAINT PK_DST_COV20_ITEM_2 PRIMARY KEY (I_ITEM_SK)
) TABLESPACE SYS_TBS_DISK_DATA;

CREATE TABLE DST_COV20_STORE_SALES_2
(
    SS_ITEM_SK        INTEGER NOT NULL,
    SS_TICKET_NUMBER  INTEGER NOT NULL,
    SS_SALES_PRICE    NUMERIC(7,2),
    CONSTRAINT PK_DST_COV20_STORE_SALES_2 PRIMARY KEY (SS_ITEM_SK, SS_TICKET_NUMBER)
) TABLESPACE SYS_TBS_DISK_DATA;

INSERT INTO DST_COV20_ITEM_2
SELECT LEVEL,
       RPAD('CLASS' || TO_CHAR(MOD(LEVEL, 97)), 50, 'X')
  FROM DUAL
CONNECT BY LEVEL <= 5000;

INSERT INTO DST_COV20_STORE_SALES_2
SELECT MOD(LEVEL, 5000) + 1,
       LEVEL,
       CASE
           WHEN MOD(LEVEL, 3) = 0 THEN NULL
           ELSE CAST(MOD(LEVEL, 10000) / 100 AS NUMERIC(7,2))
       END
  FROM DUAL
CONNECT BY LEVEL <= 250000;

ALTER SYSTEM SET __TEMP_ROW_FORMAT_MODE = 1;

SELECT /*+ TEMP_TBS_DISK USE_SORT(DST_COV20_ITEM_2, DST_COV20_STORE_SALES_2) NO_USE_HASH(DST_COV20_STORE_SALES_2) */
       COUNT(*)             AS C_HINT_M1,
       COUNT(SS_SALES_PRICE) AS C_HINT_M1_NONNULL,
       SUM(SS_SALES_PRICE)   AS S_HINT_M1
  FROM DST_COV20_ITEM_2,
       DST_COV20_STORE_SALES_2
 WHERE SS_ITEM_SK = I_ITEM_SK;

SELECT COUNT(*)              AS C_BASE_M1,
       COUNT(SS_SALES_PRICE) AS C_BASE_M1_NONNULL,
       SUM(SS_SALES_PRICE)   AS S_BASE_M1
  FROM DST_COV20_ITEM_2,
       DST_COV20_STORE_SALES_2
 WHERE SS_ITEM_SK = I_ITEM_SK;

ALTER SYSTEM SET __TEMP_ROW_FORMAT_MODE = 2;

SELECT /*+ TEMP_TBS_DISK USE_SORT(DST_COV20_ITEM_2, DST_COV20_STORE_SALES_2) NO_USE_HASH(DST_COV20_STORE_SALES_2) */
       COUNT(*)              AS C_HINT_M2,
       COUNT(SS_SALES_PRICE) AS C_HINT_M2_NONNULL,
       SUM(SS_SALES_PRICE)   AS S_HINT_M2
  FROM DST_COV20_ITEM_2,
       DST_COV20_STORE_SALES_2
 WHERE SS_ITEM_SK = I_ITEM_SK;

SELECT COUNT(*)              AS C_BASE_M2,
       COUNT(SS_SALES_PRICE) AS C_BASE_M2_NONNULL,
       SUM(SS_SALES_PRICE)   AS S_BASE_M2
  FROM DST_COV20_ITEM_2,
       DST_COV20_STORE_SALES_2
 WHERE SS_ITEM_SK = I_ITEM_SK;

ALTER SYSTEM SET __TEMP_ROW_FORMAT_MODE = 0;

DROP TABLE DST_COV20_ITEM_2;
DROP TABLE DST_COV20_STORE_SALES_2;
