-- Test Purpose: Force in-memory hash path using large HASH_AREA_SIZE and verify behavior.
-- Checks: DISTINCT_HASH results are correct and HASH_AREA_SIZE is restored.
-- Disk hash temp packed-row coverage H11: force in-memory side with larger HASH_AREA_SIZE
-- Manual reference:
--   docs/manuals/altibase/Altibase_7.1/eng/iSQL User's Manual.md
--   docs/manuals/altibase/Altibase_7.1/eng/Performance Tuning Guide.md

--+SKIP BEGIN;
DROP PROCEDURE DHASH_COV11_RESTORE_HASH_AREA;
DROP TABLE DHASH_COV11_IN;
DROP TABLE DHASH_COV11_MET;
DROP TABLE DHASH_COV11_CFG;
--+SKIP END;

CREATE TABLE DHASH_COV11_CFG
(
    OLD_HASH_AREA    BIGINT
) TABLESPACE SYS_TBS_DISK_DATA;

INSERT INTO DHASH_COV11_CFG
SELECT VALUE1
  FROM V$PROPERTY
 WHERE NAME = 'HASH_AREA_SIZE';

ALTER SYSTEM SET HASH_AREA_SIZE = 67108864;

CREATE TABLE DHASH_COV11_IN
(
    ID       INTEGER,
    K1       VARCHAR(128),
    PAD1     VARCHAR(512)
) TABLESPACE SYS_TBS_DISK_DATA;

CREATE TABLE DHASH_COV11_MET
(
    BASE_USED_TEMP_PAGE    BIGINT
) TABLESPACE SYS_TBS_DISK_DATA;

INSERT INTO DHASH_COV11_IN
SELECT LEVEL,
       'K' || LPAD(TO_CHAR(MOD(LEVEL, 400)), 4, '0'),
       RPAD('V' || TO_CHAR(MOD(LEVEL, 400)), 300, 'V')
  FROM DUAL
CONNECT BY LEVEL <= 2000;

INSERT INTO DHASH_COV11_MET
SELECT VALUE
  FROM X$TEMPINFO
 WHERE NAME = 'TOTAL USED TEMP PAGE COUNT';

SELECT /*+ TEMP_TBS_DISK DISTINCT_HASH */
       COUNT(*) AS DISTINCT_CNT
  FROM (
        SELECT DISTINCT K1
          FROM DHASH_COV11_IN
       ) D;

SELECT CASE WHEN COUNT(*) = 400 THEN 1 ELSE 0 END AS PASS_DISTINCT
  FROM (
        SELECT /*+ TEMP_TBS_DISK DISTINCT_HASH */ DISTINCT K1
          FROM DHASH_COV11_IN
       ) D;

SELECT CASE
           WHEN (
                ( SELECT VALUE
                    FROM X$TEMPINFO
                   WHERE NAME = 'TOTAL USED TEMP PAGE COUNT' )
                - ( SELECT BASE_USED_TEMP_PAGE
                      FROM DHASH_COV11_MET )
                ) <= 128
           THEN 1 ELSE 0
       END AS PASS_INMEM_USED_TEMP
  FROM DUAL;

CREATE OR REPLACE PROCEDURE DHASH_COV11_RESTORE_HASH_AREA
AS
    V_OLD_HASH_AREA BIGINT;
BEGIN
    SELECT OLD_HASH_AREA
      INTO V_OLD_HASH_AREA
      FROM DHASH_COV11_CFG;

    EXECUTE IMMEDIATE 'ALTER SYSTEM SET HASH_AREA_SIZE = ' || V_OLD_HASH_AREA;
END;
/

EXECUTE DHASH_COV11_RESTORE_HASH_AREA;

DROP PROCEDURE DHASH_COV11_RESTORE_HASH_AREA;

SELECT CASE
           WHEN VALUE1 = ( SELECT OLD_HASH_AREA FROM DHASH_COV11_CFG )
           THEN 1 ELSE 0
       END AS PASS_HASH_RESTORE
  FROM V$PROPERTY
 WHERE NAME = 'HASH_AREA_SIZE';

DROP TABLE DHASH_COV11_MET;
DROP TABLE DHASH_COV11_IN;
DROP TABLE DHASH_COV11_CFG;
