-- Test Purpose: Port altidev4/test/bug2.sql as a stable set-operation regression.
-- Checks: INTERSECT and MINUS handle VARCHAR/CHAR combinations and NULL values correctly.
-- Source: altidev4/test/bug2.sql
-- Manual reference:
--   docs/manuals/altibase/Altibase_7.1/eng/iSQL User's Manual.md
--   docs/manuals/altibase/Altibase_7.1/eng/Performance Tuning Guide.md

--+SKIP BEGIN;
DROP TABLE DST_BUG2_T1;
DROP TABLE DST_BUG2_T2;
--+SKIP END;

CREATE TABLE DST_BUG2_T1
(
    I1 VARCHAR(3) VARIABLE,
    I2 VARCHAR(3) FIXED
) TABLESPACE SYS_TBS_DISK_DATA;

CREATE TABLE DST_BUG2_T2
(
    I1 VARCHAR(3) VARIABLE,
    I2 CHAR(3)
) TABLESPACE SYS_TBS_DISK_DATA;

INSERT INTO DST_BUG2_T1 VALUES (1, 1);
INSERT INTO DST_BUG2_T1 VALUES (2, 2);
INSERT INTO DST_BUG2_T1 VALUES (0, 3);
INSERT INTO DST_BUG2_T1 VALUES (2, 4);
INSERT INTO DST_BUG2_T1 VALUES (3, 1);
INSERT INTO DST_BUG2_T1 VALUES (3, 1);
INSERT INTO DST_BUG2_T1 VALUES (4, 2);
INSERT INTO DST_BUG2_T1 VALUES (2, NULL);

INSERT INTO DST_BUG2_T2 VALUES (1, 1);
INSERT INTO DST_BUG2_T2 VALUES (2, 2);
INSERT INTO DST_BUG2_T2 VALUES (1, NULL);
INSERT INTO DST_BUG2_T2 VALUES (2, 4);
INSERT INTO DST_BUG2_T2 VALUES (3, 2);
INSERT INTO DST_BUG2_T2 VALUES (4, 8);
INSERT INTO DST_BUG2_T2 VALUES (2, 2);
INSERT INTO DST_BUG2_T2 VALUES (5, 4);

SELECT /*+ TEMP_TBS_DISK */ I1, I2
  FROM (
        SELECT I1, I2 FROM DST_BUG2_T1
        INTERSECT
        SELECT I1, I2 FROM DST_BUG2_T2
       ) X
 ORDER BY I1, I2;

SELECT /*+ TEMP_TBS_DISK */ I1, I2
  FROM (
        SELECT I1, I2 FROM DST_BUG2_T1
        MINUS
        SELECT I1, I2 FROM DST_BUG2_T2
       ) X
 ORDER BY I1, I2;

DROP TABLE DST_BUG2_T1;
DROP TABLE DST_BUG2_T2;
