-- Test Purpose: Regress the external altidev4 create/test/drop workflow as a single sql_test case.
-- Checks: The large real-world query in altidev4/tests/test.sql completes under sql_test and returns 8 rows.
-- Disk sort temp coverage BUG02: external financial-report scalar-subquery regression
-- Source SQL:
--   /home/et16/work/altidev4/tests/create.sql
--   /home/et16/work/altidev4/tests/test.sql
--   /home/et16/work/altidev4/tests/drop.sql

--+SKIP BEGIN;
DROP TABLE CA_ACCTCONFIG_MST;
DROP TABLE CA_ACGRP_DTL;
DROP TABLE CA_ACGRP_LDTL;
DROP TABLE CA_ACGRP_MST;
DROP TABLE CA_ACPE_MST;
DROP TABLE CA_CECOA_MST;
DROP TABLE CA_CE_GR;
DROP TABLE CA_COA_LDTL;
DROP TABLE CA_COA_MST;
DROP TABLE CA_DOCUTP_MST;
DROP TABLE CA_DOCU_MST;
DROP TABLE CA_GRPCAL_MST;
DROP TABLE CA_IHCH_MST;
DROP TABLE CA_PREV_INFO;
DROP TABLE CM_LANGDIC_MST;
DROP TABLE CA_CECOA_INFO;
--+SKIP END;

ALTER SYSTEM SET PREPARE_STMT_MEMORY_MAXIMUM = 314572800;
ALTER SYSTEM SET OPTIMIZER_REFINE_PREPARE_MEMORY = 0;

CREATE TABLE CA_ACCTCONFIG_MST
(
    CONSGRP_CD VARCHAR(8),
    ADOCU_CD   VARCHAR(8),
    ACCT1_CD   VARCHAR(16)
) TABLESPACE SYS_TBS_DISK_DATA;

CREATE TABLE CA_ACGRP_DTL
(
    GAAP_CD  VARCHAR(8),
    FORM_CD  VARCHAR(16),
    ACGRP_CD VARCHAR(16),
    ACCT_CD  VARCHAR(16)
) TABLESPACE SYS_TBS_DISK_DATA;

CREATE TABLE CA_ACGRP_LDTL
(
    GAAP_CD  VARCHAR(8),
    FORM_CD  VARCHAR(16),
    ACGRP_CD VARCHAR(16),
    LANG_CD  VARCHAR(8),
    ACGRP_NM VARCHAR(32)
) TABLESPACE SYS_TBS_DISK_DATA;

CREATE TABLE CA_ACGRP_MST
(
    GAAP_CD     VARCHAR(8),
    FORM_CD     VARCHAR(16),
    ACGRP_CD    VARCHAR(16),
    ACGRP_NM    VARCHAR(32),
    DRCR_CD     VARCHAR(8),
    ACGRP_LV    NUMERIC(3),
    ROOT_GRP_CD VARCHAR(16),
    CAL_TP      VARCHAR(8),
    ACGRP_FG    VARCHAR(8),
    PRINT_NO    VARCHAR(16)
) TABLESPACE SYS_TBS_DISK_DATA;

CREATE TABLE CA_ACPE_MST
(
    SETTL_YM   VARCHAR(8),
    FG_CD      VARCHAR(8),
    CORP_CD    VARCHAR(8),
    CONSGRP_CD VARCHAR(8),
    PSREL_CD   VARCHAR(8)
) TABLESPACE SYS_TBS_DISK_DATA;

CREATE TABLE CA_CECOA_INFO
(
    CEACCT_CD VARCHAR(16),
    CEACCT_NM VARCHAR(32)
) TABLESPACE SYS_TBS_DISK_DATA;

CREATE TABLE CA_CECOA_MST
(
    CEACCT_CD  VARCHAR(16),
    COACGRP_CD VARCHAR(16),
    COACCT_CD  VARCHAR(16),
    IRDS_CD    VARCHAR(8),
    DOCU_CD    VARCHAR(8),
    DATASRC_CD VARCHAR(8),
    IRDS_FG_CD VARCHAR(8),
    USE_YN     VARCHAR(2)
) TABLESPACE SYS_TBS_DISK_DATA;

CREATE TABLE CA_CE_GR
(
    SETTL_YM   VARCHAR(8),
    CONSGRP_CD VARCHAR(8),
    WRT_TP     VARCHAR(8),
    CEACCT_CD  VARCHAR(16),
    COACGRP_CD VARCHAR(16),
    BOOK_AMT   NUMERIC(19,4)
) TABLESPACE SYS_TBS_DISK_DATA;

CREATE TABLE CA_COA_LDTL
(
    GAAP_CD       VARCHAR(8),
    ACCT_CD       VARCHAR(16),
    LANG_CD       VARCHAR(8),
    ACCT_NM       VARCHAR(32),
    FULL_ACCT_TXT VARCHAR(32)
) TABLESPACE SYS_TBS_DISK_DATA;

CREATE TABLE CA_COA_MST
(
    GAAP_CD      VARCHAR(8),
    ACCT_CD      VARCHAR(16),
    ACCT_NM      VARCHAR(32),
    FULL_ACCT_NM VARCHAR(32),
    DRCR_CD      VARCHAR(8),
    ACCT_LV      NUMERIC(3),
    ROOT_ACCT_CD VARCHAR(16),
    UP_ACCT_CD   VARCHAR(16),
    FILL_YN      VARCHAR(2),
    ACCT_FG      VARCHAR(8),
    PRINT_NO     VARCHAR(16)
) TABLESPACE SYS_TBS_DISK_DATA;

CREATE TABLE CA_DOCUTP_MST
(
    DOCU_CD VARCHAR(8),
    ADJT_TP VARCHAR(8)
) TABLESPACE SYS_TBS_DISK_DATA;

CREATE TABLE CA_DOCU_MST
(
    SETTL_YM   VARCHAR(8),
    CONSGRP_CD VARCHAR(8),
    WRT_TP     VARCHAR(8),
    DOCU_CD    VARCHAR(8),
    DRCR_CD    VARCHAR(8),
    ACCT_CD    VARCHAR(16),
    DR_AMT     NUMERIC(19,4),
    CR_AMT     NUMERIC(19,4),
    SCORP_CD   VARCHAR(8),
    TCORP_CD   VARCHAR(8),
    DOCU_ST    VARCHAR(8)
) TABLESPACE SYS_TBS_DISK_DATA;

CREATE TABLE CA_GRPCAL_MST
(
    GAAP_CD      VARCHAR(8),
    FORM_CD      VARCHAR(16),
    CAL_ACGRP_CD VARCHAR(16),
    ACGRP_CD     VARCHAR(16)
) TABLESPACE SYS_TBS_DISK_DATA;

CREATE TABLE CA_IHCH_MST
(
    SETTL_YM       VARCHAR(8),
    CONSGRP_CD     VARCHAR(8),
    IRDS_CD        VARCHAR(8),
    CAPL_COACCT_CD VARCHAR(16),
    DR_ACCT2_AMT   NUMERIC(19,4),
    CR_ACCT2_AMT   NUMERIC(19,4)
) TABLESPACE SYS_TBS_DISK_DATA;

CREATE TABLE CA_PREV_INFO
(
    SETTL_YM   VARCHAR(8),
    LYSETTL_YM VARCHAR(8)
) TABLESPACE SYS_TBS_DISK_DATA;

CREATE TABLE CM_LANGDIC_MST
(
    LANG_CD     VARCHAR(8),
    LANGDIC_CD  VARCHAR(16),
    LANGDIC_TXT VARCHAR(32)
) TABLESPACE SYS_TBS_DISK_DATA;
