"""Configuration constants for Altibase SQL test runner."""

from __future__ import annotations

STATUS_PASS = "PASS"
STATUS_ORDER = "ORDER"
STATUS_FAIL = "FAIL"
STATUS_ERROR = "ERROR"
STATUS_FATAL = "FATAL"

STATUSES = [STATUS_PASS, STATUS_ORDER, STATUS_FAIL, STATUS_ERROR, STATUS_FATAL]

REASON_ORDERING_MISMATCH = "ordering_mismatch"
REASON_CONTENT_MISMATCH = "content_mismatch"
REASON_MISSING_LST = "missing_lst"
REASON_EXEC_FAILED = "exec_failed"
REASON_SERVER_DISCONNECTED = "server_disconnected"
REASON_SERVER_PORT_CLOSED = "server_port_closed"
REASON_FATAL_RECOVERY_FAILED = "fatal_recovery_failed"
REASON_TIMEOUT = "timeout"
REASON_CYCLE_INCLUDE = "cycle_include"
REASON_PATH_OUTSIDE_ROOT = "path_outside_root"
REASON_PARSE_ERROR = "parse_error"
REASON_UNKNOWN_DIRECTIVE = "unknown_directive"
REASON_INTERNAL_ERROR = "internal_error"

REASONS = [
    REASON_ORDERING_MISMATCH,
    REASON_CONTENT_MISMATCH,
    REASON_MISSING_LST,
    REASON_EXEC_FAILED,
    REASON_SERVER_DISCONNECTED,
    REASON_SERVER_PORT_CLOSED,
    REASON_FATAL_RECOVERY_FAILED,
    REASON_TIMEOUT,
    REASON_CYCLE_INCLUDE,
    REASON_PATH_OUTSIDE_ROOT,
    REASON_PARSE_ERROR,
    REASON_UNKNOWN_DIRECTIVE,
    REASON_INTERNAL_ERROR,
]

DEFAULT_SERVER_MODE = "start-once"
DEFAULT_CLEAN_MODE = "none"
DEFAULT_TIMEOUT_SEC = 60
DEFAULT_DIFF_TOOL_CHAIN = ["meld", "kdiff3", "code --diff"]
DEFAULT_VIEWDIFF_UI = "cli"
DEFAULT_PORT = 17730
DEFAULT_PORT_CHECK_TIMEOUT_SEC = 1.0
DEFAULT_FATAL_RECOVER_MAX = 1
DEFAULT_LINE_WIDTH = 96

FATAL_PATTERNS = [
    "ERR-50032",
    "Client unable to establish connection",
    "Failed to invoke the connect() system function",
    "ISQL_CONNECTION = TCP",
]

ISSUE_STATUSES = {STATUS_ORDER, STATUS_FAIL, STATUS_ERROR, STATUS_FATAL}

