-- Test Purpose: Force out-memory hash path using small HASH_AREA_SIZE and verify behavior.
-- Checks: DISTINCT_HASH results are correct and HASH_AREA_SIZE is restored.
-- Disk hash temp packed-row coverage H12: force out-memory side with minimal HASH_AREA_SIZE
-- Manual reference:
--   docs/manuals/altibase/Altibase_7.1/eng/iSQL User's Manual.md
--   docs/manuals/altibase/Altibase_7.1/eng/Performance Tuning Guide.md

--+SKIP BEGIN;
DROP TABLE DHASH_COV12_OUT;
DROP TABLE DHASH_COV12_MET;
DROP TABLE DHASH_COV12_CFG;
--+SKIP END;

CREATE TABLE DHASH_COV12_CFG
(
    OLD_HASH_AREA    BIGINT
) TABLESPACE SYS_TBS_DISK_DATA;

INSERT INTO DHASH_COV12_CFG
SELECT VALUE1
  FROM V$PROPERTY
 WHERE NAME = 'HASH_AREA_SIZE';

ALTER SYSTEM SET HASH_AREA_SIZE = 3145728;

CREATE TABLE DHASH_COV12_OUT
(
    ID       INTEGER,
    K1       VARCHAR(3200),
    PAD1     VARCHAR(3200)
) TABLESPACE SYS_TBS_DISK_DATA;

CREATE TABLE DHASH_COV12_MET
(
    BASE_USED_TEMP_PAGE    BIGINT
) TABLESPACE SYS_TBS_DISK_DATA;

INSERT INTO DHASH_COV12_OUT
SELECT LEVEL,
       'P' || LPAD(TO_CHAR(MOD(LEVEL, 5000)), 4, '0')
           || RPAD('X', 2300 + MOD(LEVEL, 5), 'X'),
       RPAD('V' || TO_CHAR(MOD(LEVEL, 3000)), 3200, 'V')
  FROM DUAL
CONNECT BY LEVEL <= 50000;

INSERT INTO DHASH_COV12_MET
SELECT VALUE
  FROM X$TEMPINFO
 WHERE NAME = 'TOTAL USED TEMP PAGE COUNT';

SELECT /*+ TEMP_TBS_DISK DISTINCT_HASH */
       COUNT(*) AS DISTINCT_CNT
  FROM (
        SELECT DISTINCT K1
          FROM DHASH_COV12_OUT
       ) D;

SELECT CASE WHEN COUNT(*) = 5000 THEN 1 ELSE 0 END AS PASS_DISTINCT
  FROM (
        SELECT /*+ TEMP_TBS_DISK DISTINCT_HASH */ DISTINCT K1
          FROM DHASH_COV12_OUT
       ) D;

SELECT CASE
           WHEN (
                ( SELECT VALUE
                    FROM X$TEMPINFO
                   WHERE NAME = 'TOTAL USED TEMP PAGE COUNT' )
                - ( SELECT BASE_USED_TEMP_PAGE
                      FROM DHASH_COV12_MET )
                ) > 256
           THEN 1 ELSE 0
       END AS PASS_OUTMEM_USED_TEMP
  FROM DUAL;

DECLARE
    V_OLD_HASH_AREA BIGINT;
    V_STMT          VARCHAR(200);
BEGIN
    SELECT OLD_HASH_AREA
      INTO V_OLD_HASH_AREA
      FROM DHASH_COV12_CFG;

    V_STMT := 'ALTER SYSTEM SET HASH_AREA_SIZE = ' || V_OLD_HASH_AREA;
    EXECUTE IMMEDIATE V_STMT;
END;
/

SELECT CASE
           WHEN VALUE1 = ( SELECT OLD_HASH_AREA FROM DHASH_COV12_CFG )
           THEN 1 ELSE 0
       END AS PASS_HASH_RESTORE
  FROM V$PROPERTY
 WHERE NAME = 'HASH_AREA_SIZE';

DROP TABLE DHASH_COV12_MET;
DROP TABLE DHASH_COV12_OUT;
DROP TABLE DHASH_COV12_CFG;
